language: c
compiler:
  - gcc
  - clang
env:
  - BINDINGS=none
matrix:
  include:
    - compiler: gcc
      language: python
      python: "2.7"
      env: BINDINGS=python
    - compiler: clang
      language: python
      python: "2.7"
      env: BINDINGS=python CC=clang
    - compiler: gcc
      language: perl
      perl: "5.18"
      env: BINDINGS=perl
    - compiler: clang
      language: perl
      perl: "5.18"
      env: BINDINGS=perl CC=clang
    - compiler: gcc
      language: perl
      perl: "5.14"
      env: BINDINGS=perl
    - compiler: clang
      language: perl
      perl: "5.14"
      env: BINDINGS=perl CC=clang
    - compiler: gcc
      language: perl
      perl: "5.10"
      env: BINDINGS=perl
    - compiler: clang
      language: perl
      perl: "5.10"
      env: BINDINGS=perl CC=clang
    - compiler: gcc
      language: php
      php: "5.5"
      env: BINDINGS=php
    - compiler: clang
      language: php
      php: "5.5"
      env: BINDINGS=php CC=clang
    - compiler: gcc
      language: php
      php: "5.4"
      env: BINDINGS=php
    - compiler: clang
      language: php
      php: "5.4"
      env: BINDINGS=php CC=clang
    - compiler: gcc
      language: dotnet
      env: BINDINGS=dotnet
    - compiler: clang
      language: dotnet
      env: BINDINGS=dotnet CC=clang
    - compiler: gcc
      language: java
      jdk: oraclejdk7
      env: BINDINGS=java
    - compiler: clang
      language: java
      jdk: oraclejdk7
      env: BINDINGS=java CC=clang
    - compiler: gcc
      language: java
      jdk: openjdk7
      env: BINDINGS=java
    - compiler: clang
      language: java
      jdk: openjdk7
      env: BINDINGS=java CC=clang
    - compiler: gcc
      language: java
      jdk: openjdk6
      env: BINDINGS=java
    - compiler: clang
      language: java
      jdk: openjdk6
      env: BINDINGS=java CC=clang
before_install:
  - sudo apt-get update -qq
  - if [ "$BINDINGS" != "none" ]; then sudo apt-get install -qq swig; fi
  - if [ "$BINDINGS" == "perl" ]; then sudo add-apt-repository ppa:dns/irc -y; sudo apt-get update -qq; sudo apt-get install -qq swig=2.0.8-1irc1~12.04; fi
  - if [ "$BINDINGS" == "python" ]; then sudo apt-get install -qq python-dev; fi
  - if [ "$BINDINGS" == "dotnet" ]; then sudo add-apt-repository ppa:directhex/monoxide -y; sudo apt-get update -qq; sudo apt-get install -qq mono-devel mono-mcs nunit nunit-console; mozroots --import --sync; fi

install: true
before_script:
  - if [ "$BINDINGS" == "php" ]; then phpenv config-add src/bindings/php/hammer.ini; fi
script: 
  - if [ "$BINDINGS" == "java" ]; then sudo scons --prefix=/usr install && mvn package -P linux; else scons bindings=$BINDINGS test; fi
notifications:
  irc: 
    channels: 
      - "irc.upstandinghackers.com#hammer"
    use_notice: true
    skip_join: true
        
