language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig php5-dev php-pear
  - sudo pear channel-discover pear.phpunit.de
  - sudo pear channel-discover pear.symfony-project.com
  - sudo pear channel-discover components.ez.no
  - sudo pear update-channels
  - sudo pear upgrade-all
  - sudo pear install --alldeps phpunit/PHPUnit
  - sudo pear install --force --alldeps phpunit/PHPUnit
before_script:
  - phpenv config-add hammer.ini
script: 
  - scons
notifications:
  irc: "irc.upstandinghackers.com#hammer"
