language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.48-dev
script: scons
notifications:
  irc: "irc.upstandinghackers.com#hammer"
