language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig php5-dev php-pear
  - sudo pear install --alldeps phpunit/PHPUnit
script: 
  - scons
notifications:
  irc: "irc.upstandinghackers.com#hammer"
