language: c
compiler:
  - gcc
  - clang
env:
  - BINDINGS=none
matrix:
  include:
    - compiler: gcc
      language: php
      php: 5.5
      env: BINDINGS=php
    - compiler: clang
      language: php
      php: 5.5
      env: BINDINGS=php
    - compiler: gcc
      language: php
      php: 5.4
      env: BINDINGS=php
    - compiler: clang
      language: php
      php: 5.4
      env: BINDINGS=php
before_install:
  - sudo apt-get update -qq
  - if [ "$BINDINGS" == "php" ]; then sudo apt-get install -qq swig php5-dev; fi
#before_script:
#  
script: 
  - scons bindings=$BINDINGS
after_script:
  - scons test
  - if [ "$BINDINGS" == "php" ]; then cp build/opt/src/bindings/php/libhammer.so `php-config --extension-dir`/hammer.so; phpenv config-add src/bindings/php/hammer.ini; LD_LIBRARY_PATH=build/opt/src phpunit --include-path build/opt/src/bindings/php -v src/bindings/php/Tests; fi
notifications:
  irc: "irc.upstandinghackers.com#hammer"
